### PR TITLE
Add basic datasets API support

### PR DESCRIPTION
**Pull request by vtourraine**
This pull-request provides a basic support for the `/datasets` endpoint.

- Add `MendeleyDataset` model class, with its custom property classes
- Implement datasets API methods (read-only):
  - list datasets with query parameters
  - list datasets with linked URL
  - fetch a dataset by ID
- Update modeller to parse JSON dataset objects
- Add test case for dataset parsing
- Update the iOS example app to browse public datasets

### Remarks

- Contrary to most API calls, and contrary to the documentation, listing datasets only returns IDs, not complete object description. This is why the first screenshot of the example app only lists IDs. The second "detail" view then fetches individual datasets to get the rest of the information.
- Contrary to most API calls, listing datasets returns an array inside a dictionary, with a single `result` key, so I had to add extra code to unbundle this (e.g. `{result: [{id: 1}, {id: 2}, {id: 3}]}`)
- The MendeleyDataset object contains sub-objects, stored as properties and arrays, with non-trivial parsing. I had to update the modeller and the object helper to parse these non-root objects (e.g. parsing `NSDate` on non-root objects).

The model is fairly complex, which makes this pull-request not so trivial. The unit tests for parsing sample data are a good guarantee that this isn't breaking anything. And this is still a basic support for datasets (read only, top-level only), but hopefully, once the foundation gets merged in, the rest should be straightforward.

Feedback, as always, is much appreciated.

### CODE REVIEW

**Comment by pweschmidt** [comment]
Hi Vincent. Thanks for that. It looks thorough and i am pleased you added unit tests. There were some minor changes to recently read tests as well?

**Comment by vtourraine** [comment]
> There were some minor changes to recently read tests as well?

Good catch! I needed to test date format parsing for the datasets, but you already implemented the same test in Recently Read. So I added a helper method on `MendeleyKitTestBaseClass` to create and configure the date formatter, and refactored the Recently Read test to use this new method. It's the exact same code, put in a common area (maybe not the best place to put it, though).

**Comment by pweschmidt** [comment]
Thanks for clarifying this Vincent. I will accept and merge the changes. We will need to do some integration testing on this as well - before we merge it into the master branch. We have a dedicated project on our internal repo. And I will write up some simple tests shortly.

**Comment by vtourraine** [comment]
Sounds great. And thank you for the quick pull-request review.

**Pull request merged**
