### PR TITLE
Fix annotations encoding/decoding for OS X

### PR DESCRIPTION
**Pull request by vtourraine**
Keep UIKit-specific methods for iOS, switch to alternatives for OS X.

### CODE REVIEW

**Comment by pweschmidt** [comment]
Thanks Vincent. Well spotted :+1:

**Comment by vtourraine** [comment]
Yes, well, the compiler spotted it for me. Thank you Xcode, then :hammer:

**Comment by pweschmidt** [comment]
I just merged it into Development and then master. v0.9.14 has the code included

**Comment by vtourraine** [comment]
Wahoo, very responsive. Thanks Peter!

**Pull request merged**
